name: simple_html_css
description: This package allows you to use simple HTML and inline CSS styles to style your text in flutter. A fork of css_text package.
version: 4.0.1
publish_to: https://unpub.plentific.com/
repository: https://github.com/plentific/simple_html_css_flutter

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  html_unescape: ^2.0.0
  xml: ^6.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
