name: simple_html_css
description: This package allows you to use simple HTML and inline CSS styles to style your text in flutter. A fork of css_text package.
version: 5.0.0
publish_to: https://unpub.plentific.com/
repository: https://github.com/plentific/simple_html_css_flutter

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
